spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
          initial-size: 3
          max-active: 10
          min-idle: 3
  rabbitmq:
    host: 127.0.0.1
    port: 5672
#    username: guest
#    password: guest
    virtual-host: /
    publisher-confirms: true



