spring:
  profiles:
    active: dev
  jpa:
    database : MYSQL
    show-sql : true
    properties:
      hibernate:
#        dialect: org.hibernate.spatial.dialect.mysql.MySQL5InnoDBSpatialDialect
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect



    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy


# log default level
logging:
  level:
    root: info

